server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # DB - Local
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/kys
#    username: ENC(MzVYb4ZviEJWdLvVFw0CSA==)
#    password: ENC(5S02fsms4i0sL9H7seXhGA==)
#    schema-name: kys
  # DB - Remote
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://monsu1016.cafe24.com:3306/monsu1016
    username: ENC(eAdrBOt3oVrDRFHPDxMDnCTqHzLnVKbG)
    password: ENC(xZG6QLvv40VdE6bY02CZDtHb4nzCRGaz)
    schema-name: monsu1016

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(JBGxcEw+2RG3bVGGnkc55wDbacOnZt92)
    password: ENC(TaXgPcijkClZQFb8HAhy11RMZHFvfaDDVHtt6RdbRpE=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# AES256
aes:
  256:
    key: ENC(OxYzCFD5ylp2steDZ/UgZBxDo4UmkYY/07qKw9le6vAy1OJoR9eMI4poOmKoyhEQ)
# 설정 파일 암호화
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
#    bean: encryptorBean

# SMS
naver:
  sms:
    accessKey: ENC(FY3uih/zl45Y2ip+4d8kGkoCVXH0XJfOq60tlntWrIA=)
    serviceId: ENC(XrkwVv8SsZNgoxLcY9AFuyydYEhHIiQkL39jQGu8Xx2jnynz+iFnAfL7h3a54qQl)
    secretKey: ENC(Fdc8to83sdr6CQVbx+vrq1d39ZNefbWYyt2JILsdQmUi1+ilbYV4X+jioPsimotMnvNejcWfT10=)
    senderPhoneNum: ENC(8TAbR7DL+h5KGI1uA8MxpEcfvcLUNIMF)
mybatis:
  type-aliases-package: com.hotel.common
  mapper-locations: mapper/**/*.xml

JWT:
  secret: ENC(Hq4qsMCxhuP5AhdzcOQ/JXrT3RdnQAeqgtTNYybJTqhKYlzHDW+0+70tKbyYW0yxIKyC/RI58wLC7UX+J+hF756lIZIj4YxTpnSOiZERp9TmpB1YUJUplEz5/J8ZlW5V)

# AWS
cloud:
  aws:
    credentials:
      accessKey: ENC(l0JjuxzacYaVDZfI0MC5HGDc5ZH/WBewTWOfPcCOdPo=)
      secretKey: ENC(ZDvKIvg90AOQfX9NRHF/Ivzrw5O7km9M99gEAGL/foDafEW0PpDULGX/In50RizSh1OycnVWNjQ=)
    s3:
      bucket: ENC(ZDhm1vNK1nWGhfEWq+ETXDsHR+nRQGsJt1LudfoNDm0=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

# 공공데이터포탈
odcloud:
  serviceKey: ENC(FmB3m1M9Q5Ocu6+QkypSbBQVJjs2+s+0ytMIEgF4EOeaadpebNlbkq9J8KoegAG4PHmCaJ0pUxBznxRwWRMvlzHiX+OAlHqcVPng3Mx7+97voaTtBEcCLZ1tcQ4y3zxV9LKuBBEbS8F9pIp2VBhQ/g==)

kakao:
  secretKey: KakaoAK e3c6a35b694e94ec63c0afca1411ae0c

search:
  distance: 1000

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error