server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
#    username: admin
#    password: admin

# AWS Key 파일, JWT개인키등 - 서버에 config로 관리하고 여기엔 해당 위치만 표기
